//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualEnvironment.Platform {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualEnvironment.Platform.Sources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching the virtual disk.
        /// </summary>
        internal static string DiskpartAttach {
            get {
                return ResourceManager.GetString("DiskpartAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment as drive {0}.
        /// </summary>
        internal static string DiskpartAttachDiskpart {
            get {
                return ResourceManager.GetString("DiskpartAttachDiskpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching the virtual disk failed.
        /// </summary>
        internal static string DiskpartAttachFailed {
            get {
                return ResourceManager.GetString("DiskpartAttachFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compaction of the virtual disk.
        /// </summary>
        internal static string DiskpartCompact {
            get {
                return ResourceManager.GetString("DiskpartCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual disk and file system are compacted.
        /// </summary>
        internal static string DiskpartCompactDiskpart {
            get {
                return ResourceManager.GetString("DiskpartCompactDiskpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compaction of the virtual disk failed.
        /// </summary>
        internal static string DiskpartCompactFailed {
            get {
                return ResourceManager.GetString("DiskpartCompactFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of the virtual disk.
        /// </summary>
        internal static string DiskpartCreate {
            get {
                return ResourceManager.GetString("DiskpartCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating virtual disk.
        /// </summary>
        internal static string DiskpartCreateDiskpart {
            get {
                return ResourceManager.GetString("DiskpartCreateDiskpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of the virtual disk failed.
        /// </summary>
        internal static string DiskpartCreateFailed {
            get {
                return ResourceManager.GetString("DiskpartCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File system are initialized.
        /// </summary>
        internal static string DiskpartCreateInitializationFileSystem {
            get {
                return ResourceManager.GetString("DiskpartCreateInitializationFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaching the virtual disk.
        /// </summary>
        internal static string DiskpartDetach {
            get {
                return ResourceManager.GetString("DiskpartDetach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigning the drive and detaching the virtual disk.
        /// </summary>
        internal static string DiskpartDetachDiskpart {
            get {
                return ResourceManager.GetString("DiskpartDetachDiskpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaching the virtual disk failed.
        /// </summary>
        internal static string DiskpartDetachFailed {
            get {
                return ResourceManager.GetString("DiskpartDetachFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive already exists.
        /// </summary>
        internal static string DiskpartDriveAlreadyExists {
            get {
                return ResourceManager.GetString("DiskpartDriveAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual disk already exists as a file.
        /// </summary>
        internal static string DiskpartFileAlreadyExists {
            get {
                return ResourceManager.GetString("DiskpartFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file can be found for the virtual disk.
        /// </summary>
        internal static string DiskpartFileNotExists {
            get {
                return ResourceManager.GetString("DiskpartFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred.
        /// </summary>
        internal static string DiskpartUnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("DiskpartUnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching the virtual environment.
        /// </summary>
        internal static string WorkerAttach {
            get {
                return ResourceManager.GetString("WorkerAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch processing has failed.
        /// </summary>
        internal static string WorkerAttachBatchFailed {
            get {
                return ResourceManager.GetString("WorkerAttachBatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration of the virtual environment.
        /// </summary>
        internal static string WorkerAttachEnvironmentSetup {
            get {
                return ResourceManager.GetString("WorkerAttachEnvironmentSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching the virtual environment failed.
        /// </summary>
        internal static string WorkerAttachFailed {
            get {
                return ResourceManager.GetString("WorkerAttachFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching the virtual environment
        ///Programs and services are established.
        /// </summary>
        internal static string WorkerAttachText {
            get {
                return ResourceManager.GetString("WorkerAttachText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch processing no longer responds.
        /// </summary>
        internal static string WorkerBatchFreezeDetection {
            get {
                return ResourceManager.GetString("WorkerBatchFreezeDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary files are cleaned.
        /// </summary>
        internal static string WorkerCompactCleanFilesystem {
            get {
                return ResourceManager.GetString("WorkerCompactCleanFilesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compaction of the virtual environment
        ///Virtual disk and file system are compacted.
        /// </summary>
        internal static string WorkerCompactText {
            get {
                return ResourceManager.GetString("WorkerCompactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of the virtual environment
        ///Virtual disk and file system are initialized.
        /// </summary>
        internal static string WorkerCreateText {
            get {
                return ResourceManager.GetString("WorkerCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaching the virtual environment.
        /// </summary>
        internal static string WorkerDetach {
            get {
                return ResourceManager.GetString("WorkerDetach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch processing has failed.
        /// </summary>
        internal static string WorkerDetachBatchFailed {
            get {
                return ResourceManager.GetString("WorkerDetachBatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaching is blocked by {0}
        ///{1}.
        /// </summary>
        internal static string WorkerDetachBlocked {
            get {
                return ResourceManager.GetString("WorkerDetachBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaching the virtual environment failed.
        /// </summary>
        internal static string WorkerDetachFailed {
            get {
                return ResourceManager.GetString("WorkerDetachFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaching the virtual environment
        ///Programs and services are terminated.
        /// </summary>
        internal static string WorkerDetachText {
            get {
                return ResourceManager.GetString("WorkerDetachText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of shortcuts.
        /// </summary>
        internal static string WorkerShortcuts {
            get {
                return ResourceManager.GetString("WorkerShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of the shortcuts
        ///The usual functions are initialized.
        /// </summary>
        internal static string WorkerShortcutsText {
            get {
                return ResourceManager.GetString("WorkerShortcutsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully completed.
        /// </summary>
        internal static string WorkerSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("WorkerSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred.
        /// </summary>
        internal static string WorkerUnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("WorkerUnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [A-Z]: [create|attach|detach|...].
        /// </summary>
        internal static string WorkerUsage {
            get {
                return ResourceManager.GetString("WorkerUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seanox Virtual Environment [0.0.0 00000000].
        /// </summary>
        internal static string WorkerVersion {
            get {
                return ResourceManager.GetString("WorkerVersion", resourceCulture);
            }
        }
    }
}
