//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualEnvironment.Platform {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualEnvironment.Platform.Sources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully completed.
        /// </summary>
        internal static string ApplicationCompleted {
            get {
                return ResourceManager.GetString("ApplicationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred.
        /// </summary>
        internal static string ApplicationUnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("ApplicationUnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [A-Z]: [create|attach|detach|...].
        /// </summary>
        internal static string ApplicationUsage {
            get {
                return ResourceManager.GetString("ApplicationUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seanox Virtual Environment [{0} {1}].
        /// </summary>
        internal static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching virtual disk.
        /// </summary>
        internal static string DiskpartAttach {
            get {
                return ResourceManager.GetString("DiskpartAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual disk attachment aborted.
        /// </summary>
        internal static string DiskpartAttachAbort {
            get {
                return ResourceManager.GetString("DiskpartAttachAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning drive {0}.
        /// </summary>
        internal static string DiskpartAttachDiskpart {
            get {
                return ResourceManager.GetString("DiskpartAttachDiskpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing drive {0} assigned.
        /// </summary>
        internal static string DiskpartAttachExistingDrive {
            get {
                return ResourceManager.GetString("DiskpartAttachExistingDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual disk attachment failed.
        /// </summary>
        internal static string DiskpartAttachFailed {
            get {
                return ResourceManager.GetString("DiskpartAttachFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compacting virtual disk.
        /// </summary>
        internal static string DiskpartCompact {
            get {
                return ResourceManager.GetString("DiskpartCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual disk and file system compacted.
        /// </summary>
        internal static string DiskpartCompactDiskpart {
            get {
                return ResourceManager.GetString("DiskpartCompactDiskpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual disk compaction failed.
        /// </summary>
        internal static string DiskpartCompactFailed {
            get {
                return ResourceManager.GetString("DiskpartCompactFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating virtual disk.
        /// </summary>
        internal static string DiskpartCreate {
            get {
                return ResourceManager.GetString("DiskpartCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing virtual disk.
        /// </summary>
        internal static string DiskpartCreateDiskpart {
            get {
                return ResourceManager.GetString("DiskpartCreateDiskpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual disk creation failed.
        /// </summary>
        internal static string DiskpartCreateFailed {
            get {
                return ResourceManager.GetString("DiskpartCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File system initialized.
        /// </summary>
        internal static string DiskpartCreateInitializationFileSystem {
            get {
                return ResourceManager.GetString("DiskpartCreateInitializationFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaching virtual disk.
        /// </summary>
        internal static string DiskpartDetach {
            get {
                return ResourceManager.GetString("DiskpartDetach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigning drive and detaching virtual disk.
        /// </summary>
        internal static string DiskpartDetachDiskpart {
            get {
                return ResourceManager.GetString("DiskpartDetachDiskpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual disk detachment failed.
        /// </summary>
        internal static string DiskpartDetachFailed {
            get {
                return ResourceManager.GetString("DiskpartDetachFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive already exists.
        /// </summary>
        internal static string DiskpartDriveAlreadyExists {
            get {
                return ResourceManager.GetString("DiskpartDriveAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive already used.
        /// </summary>
        internal static string DiskpartDriveAlreadyUsed {
            get {
                return ResourceManager.GetString("DiskpartDriveAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual disk file already exists.
        /// </summary>
        internal static string DiskpartFileAlreadyExists {
            get {
                return ResourceManager.GetString("DiskpartFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file found for virtual disk.
        /// </summary>
        internal static string DiskpartFileNotExists {
            get {
                return ResourceManager.GetString("DiskpartFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching virtual environment.
        /// </summary>
        internal static string ServiceAttach {
            get {
                return ResourceManager.GetString("ServiceAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch process failed.
        /// </summary>
        internal static string ServiceAttachBatchFailed {
            get {
                return ResourceManager.GetString("ServiceAttachBatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize files.
        /// </summary>
        internal static string ServiceAttachCustomizeFiles {
            get {
                return ResourceManager.GetString("ServiceAttachCustomizeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring virtual environment.
        /// </summary>
        internal static string ServiceAttachEnvironment {
            get {
                return ResourceManager.GetString("ServiceAttachEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual environment attachment failed.
        /// </summary>
        internal static string ServiceAttachFailed {
            get {
                return ResourceManager.GetString("ServiceAttachFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize host file system.
        /// </summary>
        internal static string ServiceAttachHostFilesystem {
            get {
                return ResourceManager.GetString("ServiceAttachHostFilesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs and services established.
        /// </summary>
        internal static string ServiceAttachText {
            get {
                return ResourceManager.GetString("ServiceAttachText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch process failed.
        /// </summary>
        internal static string ServiceBatchFailed {
            get {
                return ResourceManager.GetString("ServiceBatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch process unresponsive.
        /// </summary>
        internal static string ServiceBatchFreezeDetection {
            get {
                return ResourceManager.GetString("ServiceBatchFreezeDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compacting virtual environment.
        /// </summary>
        internal static string ServiceCompact {
            get {
                return ResourceManager.GetString("ServiceCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning temporary files.
        /// </summary>
        internal static string ServiceCompactCleanFilesystem {
            get {
                return ResourceManager.GetString("ServiceCompactCleanFilesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual disk and file system compacted.
        /// </summary>
        internal static string ServiceCompactText {
            get {
                return ResourceManager.GetString("ServiceCompactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating virtual environment.
        /// </summary>
        internal static string ServiceCreate {
            get {
                return ResourceManager.GetString("ServiceCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual disk and file system initialized.
        /// </summary>
        internal static string ServiceCreateText {
            get {
                return ResourceManager.GetString("ServiceCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaching virtual environment.
        /// </summary>
        internal static string ServiceDetach {
            get {
                return ResourceManager.GetString("ServiceDetach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaching is blocked by {0}
        ///{1}.
        /// </summary>
        internal static string ServiceDetachBlocked {
            get {
                return ResourceManager.GetString("ServiceDetachBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual environment detachment failed.
        /// </summary>
        internal static string ServiceDetachFailed {
            get {
                return ResourceManager.GetString("ServiceDetachFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore host file system.
        /// </summary>
        internal static string ServiceDetachHostFilesystem {
            get {
                return ResourceManager.GetString("ServiceDetachHostFilesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs and services terminated.
        /// </summary>
        internal static string ServiceDetachText {
            get {
                return ResourceManager.GetString("ServiceDetachText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring virtual environment.
        /// </summary>
        internal static string ServiceRestore {
            get {
                return ResourceManager.GetString("ServiceRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending changes to the host system are restored.
        /// </summary>
        internal static string ServiceRestoreText {
            get {
                return ResourceManager.GetString("ServiceRestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating shortcuts.
        /// </summary>
        internal static string ServiceShortcuts {
            get {
                return ResourceManager.GetString("ServiceShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usual functions initialized.
        /// </summary>
        internal static string ServiceShortcutsText {
            get {
                return ResourceManager.GetString("ServiceShortcutsText", resourceCulture);
            }
        }
    }
}
